name: example
description: An absolute bare-bones web app.
version: 0.0.1

dependencies:
  livereload:

dev_dependencies:
  build_runner:
  build_web_compilers:

environment:
  sdk: '>=2.0.0-dev <2.0.0'
