name: livereload
description: A simple web development server which supports rewrite and live-reload.
version: 0.1.0+1
homepage: https://github.com/furrary/livereload
author: Feu <furrary@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  args: ^1.3.0
  mime: ^0.9.0
  path: ^1.5.0
  shelf: ^0.7.0
  shelf_proxy: ^0.1.0
  shelf_web_socket: ^0.2.0
  web_socket_channel: ^1.0.0
